name: oops
version: '0.1.0.0'
category: Web
author: NoRedInk
maintainer: eng@noredink.com
copyright: 2017 NoRedInk
license: BSD3
dependencies:
- base == 4.10.1.0
- cmark == 0.5.6
- heredoc == 0.2.0.0
- prettyprinter == 1.2.0.1
- prettyprinter-ansi-terminal == 1.1.1.2
- template-haskell == 2.12.0.0
- terminal-size == 0.3.2.1
- text == 1.2.2.2
default-extensions:
- LambdaCase
- NamedFieldPuns
- OverloadedStrings
- PackageImports
ghc-options:
- -Wall
- -Werror
library:
  source-dirs: src
